name: seelai_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_database: ^12.0.3
  provider: ^6.1.5+1
  firebase_messaging: ^16.1.1
  firebase_core: ^4.2.0
  camera: ^0.11.4
  intl: ^0.20.2
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  animated_splash_screen: ^1.3.0
  lottie: ^3.3.2
  flutter_native_splash: ^2.4.7
  flutter_osm_plugin: ^1.4.2
  firebase_storage: ^13.0.4
  http: ^1.6.0
  crypto: ^3.0.7
  geolocator: ^14.0.1
  google_mlkit_text_recognition: ^0.15.0
  flutter_tts: ^4.2.3
  tflite_flutter: ^0.12.1
  image_picker: ^1.2.1
  image: ^4.5.4
  flutter_vision: ^2.0.0
  audioplayers: ^6.5.1
  timeago: ^3.7.1
  google_sign_in: ^7.2.0
  video_player: ^2.10.1
  geocoding: ^4.0.0
  flutter_webrtc: ^1.3.1
  vibration: ^3.1.8
  fl_chart: ^1.2.0
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.4
  uuid: ^4.5.3
  pdf: ^3.12.0
  printing: ^5.14.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/object_model/objects.tflite
    - assets/object_model/labels.txt
    - assets/face_model/face_detection.tflite
    - assets/face_model/labels.txt
    - assets/face_model/face.tflite
    - assets/object_model/seelai-objects.tflite
    - assets/face_model/final_face.tflite
    - assets/emergency_images/
    - assets/icons/
    - assets/video/sample_vid.mp4
    - assets/seelai-icons/
    - assets/onboarding_icons/
    - assets/seelai_app_logo/

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/seelai_app_logo/seelai_app_logo.png"

  adaptive_icon_background: "#8B5CF6"
  adaptive_icon_foreground: "assets/seelai_app_logo/seelai_app_logo.png"

flutter_native_splash:
  color: "#FAF5FF"
  android: true
  ios: true
