// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT2MWz7kLuVqe35mgfLHj0EV14rkT5i9A',
    appId: '1:697931553557:web:a8a4024a148b50cd15a71c',
    messagingSenderId: '697931553557',
    projectId: 'seelai-4b026',
    authDomain: 'seelai-4b026.firebaseapp.com',
    databaseURL: 'https://seelai-4b026-default-rtdb.firebaseio.com',
    storageBucket: 'seelai-4b026.firebasestorage.app',
    measurementId: 'G-ZE095E4J7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpdRUgnEgn3Ox81MQGEe07ydZoTIWNk9M',
    appId: '1:697931553557:android:4a747185ba437d8015a71c',
    messagingSenderId: '697931553557',
    projectId: 'seelai-4b026',
    databaseURL: 'https://seelai-4b026-default-rtdb.firebaseio.com',
    storageBucket: 'seelai-4b026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsISefwlH-HxTi_kduI1ADQqiuhu-TCHY',
    appId: '1:697931553557:ios:ab5f9fa0515e77e115a71c',
    messagingSenderId: '697931553557',
    projectId: 'seelai-4b026',
    databaseURL: 'https://seelai-4b026-default-rtdb.firebaseio.com',
    storageBucket: 'seelai-4b026.firebasestorage.app',
    iosBundleId: 'com.example.seelaiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsISefwlH-HxTi_kduI1ADQqiuhu-TCHY',
    appId: '1:697931553557:ios:ab5f9fa0515e77e115a71c',
    messagingSenderId: '697931553557',
    projectId: 'seelai-4b026',
    databaseURL: 'https://seelai-4b026-default-rtdb.firebaseio.com',
    storageBucket: 'seelai-4b026.firebasestorage.app',
    iosBundleId: 'com.example.seelaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT2MWz7kLuVqe35mgfLHj0EV14rkT5i9A',
    appId: '1:697931553557:web:3a5ef18fa4ba4e8f15a71c',
    messagingSenderId: '697931553557',
    projectId: 'seelai-4b026',
    authDomain: 'seelai-4b026.firebaseapp.com',
    databaseURL: 'https://seelai-4b026-default-rtdb.firebaseio.com',
    storageBucket: 'seelai-4b026.firebasestorage.app',
    measurementId: 'G-VBVNW2FM65',
  );
}
